### ISSUE TITLE
Logo sometimes loads improperly

### ISSUE THREAD

**Issue by James-Reilly** [jimmified/jimmify-web#26]
![screen shot 2017-03-25 at 11 03 08 pm](https://cloud.githubusercontent.com/assets/7049463/24437490/1fb4a3b8-13f6-11e7-879a-c67072fcad0e.png)

**Comment by jlyneu** [comment]
Current guess is that the browser had the old version of the page cached and something strange happened when visiting the page again for the first time with the updated version of the page, but we're not certain
