### ISSUE TITLE
Redesign link results like google knowledge graph cards

### ISSUE THREAD

**Issue by James-Reilly** [jimmified/jimmify-web#27]
Maybe something like how the results are formatted with an info card on [google search](https://www.google.com/search?q=president+of+the+united+states&oq=president+of+the+un&aqs=chrome.0.0j69i57j0l4.4276j0j7&sourceid=chrome&ie=UTF-8). 

Where the card would be the jimmy response, but the links returned would be the results below.  This would give a clear distinction between the official jimmy response and the other links.

**Comment by jlyneu** [comment]
This is merged into master now. Feel free to play around with it and see if you want to change it
