### ISSUE TITLE
I'm feeling jimmy button

### ISSUE THREAD

**Issue by tylerkrupicka** [jimmified/jimmify-web#4]
We need to think of something funny for the IFJ button. Maybe a burst of confetti or something. Would also be funny to imitate the google IFL button spinner but all of the options are jimmy. We can probably find that on codepen.

**Comment by jlyneu** [comment]
https://github.com/jimmified/jimmify-web/commit/147d4f7468423bd16e1697e5dddde1b7912750e8 When the user's mouse enters the IFJ button, the text spins a random number of times (no more than 4) in a random direction. When the user clicks on the IFJ button, the logo rotates to a new logo.

**Comment by tylerkrupicka** [comment]
love it
