### ISSUE TITLE
Change search logo behavior

### ISSUE THREAD

**Issue by tylerkrupicka** [jimmified/jimmify-web#6]
I've had a number of people not know search providers, so they got a little confused when they got one of the less known ones like duck duck or baidu. Everyone knows google however, so I think we should make google the default one and just switch to a new one every 5-10 seconds so that people understand the others are search providers as well.

**Comment by jlyneu** [comment]
https://github.com/jimmified/jimmify-web/commit/13aee8bd5e3b979f4cf19a7497cb0ee10566bbcc currently on gh-pages. Logo starts as google then rotates to new logo on mouse enter or click.

**Comment by jlyneu** [comment]
https://github.com/jimmified/jimmify-web/commit/147d4f7468423bd16e1697e5dddde1b7912750e8 Logo now only changes after clicking the "I'm Feeling Jimmy" button.
