### ISSUE TITLE
Add validation

### ISSUE THREAD

**Issue by tylerkrupicka** [jimmified/jimmify-web#9]
Add some text input field limits to match the server. 255 chars for searches, 800 chars for answers.

**Comment by jlyneu** [comment]
Added 255 char limit for searches - https://github.com/jimmified/jimmify-web/commit/fa0971fa21288562b87c904b2bfa147373343db5
Added 800 char limit for answers - https://github.com/jimmified/jimmify-web/commit/a87e12feb1ceb918eef90f2adec26cd0bd61c8f6

**Comment by tylerkrupicka** [comment]
awesome
